development:
  host: localhost
  database: bidder_development

test:
  host: localhost
  database: bidder_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
